# BUILDER

FROM rust:1.53 AS builder

WORKDIR /app

ARG service

COPY . .
RUN rustup component add rustfmt
RUN cargo build \
    --bin "gubernator_cri_mock_${service}" \
    --verbose \
    --release

# RUNNER

FROM rust:1.53 AS runner

WORKDIR /app

ARG service
ARG port

ENV PORT $port
ENV RUST_LOG info

EXPOSE $port

COPY --from=builder \
    "/app/target/release/gubernator_cri_mock_${service}" \
    "/usr/local/bin/mockedservice"

ENTRYPOINT [ "mockedservice" ]