services:
  gubernator-cri-mock-image:
    image: gubernator-cri-mock-image:latest
    build:
      context: .
      dockerfile: Dockerfile.mock
      args:
        service: "image"
        port: "548"
    environment:
      PORT: "548"
      RUST_LOG: "info"
    ports:
      - 548:548
  gubernator-cri-mock-runtime:
    image: gubernator-cri-mock-runtime:latest
    build:
      context: .
      dockerfile: Dockerfile.mock
      args:
        service: "runtime"
        port: "549"
    environment:
      PORT: "549"
      RUST_LOG: "info"
    ports:
      - 549:549
