[package]
name = "gubernator"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"

[build-dependencies]
tonic-build = "0.5"

[lib]
name = "gubernator"
path = "src/lib.rs"

[[bin]]
name = "gubernator"
path = "src/cli/mod.rs"
