name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup mock environment
        run: docker-compose up --build
      - name: Run tests
        run: cargo test --verbose
      - name: Teardown mock environment
        run: docker-compose down
